name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Deploy
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git config --global credential.helper store
          echo "https://${{ secrets.GITHUB_TOKEN }}:x-oauth-basic@github.com/g0rillaa/CSIT314Project.git" > ~/.git-credentials
          npm run deploy
        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
